# Generated by Django 3.1.7 on 2021-02-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='PLN', max_length=3)),
                ('reference', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('FD', 'Failed'), ('PG', 'Panding'), ('CT', 'Complete')], default='PG', max_length=2)),
                ('method', models.CharField(choices=[('NL', 'Normal'), ('EX', 'Express')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_transfers', to='account.bankaccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_transfers', to='account.bankaccount')),
            ],
        ),
    ]
