# Generated by Django 3.1.7 on 2021-02-25 14:47

import creditcards.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('number', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('expires_date', creditcards.models.CardExpiryField(default='01/25', verbose_name='expiration date')),
                ('code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
                ('pin', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('daily_online_limit', models.PositiveIntegerField(blank=True, default=2000, null=True)),
                ('daily_withdrawal_limit', models.PositiveIntegerField(default=2000)),
                ('monthly_online_limit', models.PositiveIntegerField(default=5000)),
                ('monthly_withdrawal_limit', models.PositiveIntegerField(default=5000)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='account.bankaccount')),
            ],
        ),
    ]
